export enum ValidationTypes {
	FIRST_NAME = 'FIRST_NAME',
	SECOND_NAME = 'SECOND_NAME',
	LOGIN = 'LOGIN',
	EMAIL = 'EMAIL',
	PASSWORD = 'PASSWORD',
	PASSWORD_REPEAT = 'PASSWORD_REPEAT',
	PASSWORD_NEW = 'PASSWORD_NEW',
	PASSWORD_OLD = 'PASSWORD_OLD',
	PHONE = 'PHONE',
	NAME_IN_CHAT = 'NAME_IN_CHAT',
}

export enum ParseDateTypes {
	DAY_MONTH=	'DAY_MONTH'
}
